### ISSUE TITLE
[Bug] Limitless 1.5.1 with 1.17.1 crashes on startup from kbootstrap

### ISSUE THREAD

**Issue by craftingmod** [auoeke/limitless#50]
Version: Minecraft 1.17.1, Fabric API 0.39.2+1.17
* Mods
```
[14:48:00] [main/INFO]: [FabricLoader] Loading 147 mods:
	- advanced_runtime_resource_pack@0.4.3
	- advancednbttooltip@1.6.0+build.4-1.17
	- advancementinfo@1.17.1-fabric0.36.1-1.2.1
	- amecsapi@1.1.4+mc21w16a
	- appleskin@mc1.17-2.1.3
	- architectury@2.4.26
	- autoconfig1u@3.2.2
	- autofish@0.9.3
	- beenfo@1.17.1-fabric0.36.1-1.3.2
	- betterbiomeblend@1.17.0-1.1.4-fabric
	- betterf3@1.1.5
	- capes@1.2.1
	- cem@0.6.2
	- cloth-basic-math@0.5.1
	- cloth-config2@5.0.38
	- clumps@fabric-1.17.1-7.0.5
	- coat@1.0.0-beta.11
	- colormatic@2.2.10+mc.1.17.1
	- com_velocitypowered_velocity-native@1.1.0-SNAPSHOT
	- compactstatuseffects@2.0.1
	- completeconfig@1.1.0
	- cr-compass-ribbon@2.7.3+1.17
	- crowdin-translate@1.3+1.17
	- ctm@0.5.1+1.17
	- cullleaves@2.2.0
	- enhancedblockentities@0.4.1+1.17
	- entityculling@1.3.3
	- entityoutliner@1.2.0
	- fabric@0.39.2+1.17
	- fabric-api-base@0.3.0+a02b446313
	- fabric-api-lookup-api-v1@1.3.0+2f75c6ce18
	- fabric-biome-api-v1@3.2.0+b06cb95b18
	- fabric-blockrenderlayer-v1@1.1.5+a02b446318
	- fabric-command-api-v1@1.1.3+5ab9934c68
	- fabric-commands-v0@0.2.2+92519afa18
	- fabric-containers-v0@0.1.12+a02b446318
	- fabric-content-registries-v0@0.3.0+211ddf9518
	- fabric-crash-report-info-v1@0.1.5+be9da31018
	- fabric-dimensions-v1@2.0.11+6cefd57718
	- fabric-entity-events-v1@1.2.2+62e33f4118
	- fabric-events-interaction-v0@0.4.9+a722d8c018
	- fabric-events-lifecycle-v0@0.2.1+92519afa18
	- fabric-game-rule-api-v1@1.0.7+6cefd57718
	- fabric-item-api-v1@1.2.4+a02b44633d
	- fabric-item-groups-v0@0.2.10+b7ab612118
	- fabric-key-binding-api-v1@1.0.4+a02b446318
	- fabric-keybindings-v0@0.2.2+36b77c3e18
	- fabric-language-kotlin@1.6.4+kotlin.1.5.30
	- fabric-lifecycle-events-v1@1.4.4+a02b44633d
	- fabric-loot-tables-v1@1.0.4+a02b446318
	- fabric-mining-levels-v0@0.1.3+92519afa18
	- fabric-models-v0@0.3.0+a02b446318
	- fabric-networking-api-v1@1.0.13+2e8bd82f18
	- fabric-networking-blockentity-v0@0.2.11+a02b446318
	- fabric-networking-v0@0.3.2+92519afa18
	- fabric-object-builder-api-v1@1.10.9+b7ab612118
	- fabric-object-builders-v0@0.7.3+a02b446318
	- fabric-particles-v1@0.2.4+a02b446318
	- fabric-registry-sync-v0@0.7.10+e2961fee18
	- fabric-renderer-api-v1@0.4.4+5f02c96918
	- fabric-renderer-indigo@0.4.8+a02b446318
	- fabric-renderer-registries-v1@3.2.1+b06cb95b18
	- fabric-rendering-data-attachment-v1@0.1.5+a02b446313
	- fabric-rendering-fluids-v1@0.1.13+a02b446318
	- fabric-rendering-v0@1.1.2+92519afa18
	- fabric-rendering-v1@1.8.0+b06cb95b18
	- fabric-resource-loader-v0@0.4.8+a00e834b18
	- fabric-screen-api-v1@1.0.4+155f865c18
	- fabric-screen-handler-api-v1@1.1.8+a02b446318
	- fabric-structure-api-v1@1.1.13+5ab9934c18
	- fabric-tag-extensions-v0@1.2.1+b06cb95b68
	- fabric-textures-v0@1.0.6+a02b446318
	- fabric-tool-attribute-api-v1@1.2.12+b7ab61213d
	- fabric-transfer-api-v1@1.1.2+96bf6a7e18
	- fabricasmtools@0.4.0
	- fabricloader@0.11.6
	- flighthud@${version}
	- gbfabrictools@1.3.4+1.17
	- here-be-no-dragons@1.0.0
	- horsestatsvanilla@4.1.8
	- hydrogen@0.3
	- indium@1.0.0+mc1.17.1
	- inventoryhud@3.4.0
	- inventoryprofilesnext@1.0.0
	- iris@1.1.1
	- jankson@3.0.1+j1.2.0
	- java@16
	- kbootstrap@0.1.0
	- krypton@0.1.4
	- lambdabettergrass@1.2.1+1.17
	- lambdynlights@2.0.2+1.17
	- lazydfu@0.1.2
	- libgui@4.0.0-beta.4+1.17-rc1
	- libninepatch@1.1.0
	- limitless@1.5.1
	- litematica@0.0.0-dev.20210713.103711
	- lithium@0.7.4
	- loading-timer@1.5.0-Beta1
	- malilib@0.10.0-dev.24
	- minecraft@1.17.1
	- minihud@0.19.0-dev.20210707.150016
	- mm@2.2
	- modmenu@2.0.5
	- mojangster@1.17-1.3.0
	- mousewheelie@1.7.3-newconfig.3+mc1.17.1-pre1
	- multiconnect@1.4.15
	- multiconnect-api@1.4.15
	- nbttooltip@1.4.0-fabric
	- net_auoeke_shortcode@0.4.1
	- net_gudenau_lib_unsafe@1.4.3
	- notenoughcrashes@3.4.4+1.17
	- now-playing@1.2.0
	- org_aperlambda_lambdajcommon@1.8.1
	- org_jetbrains_kotlin_kotlin-reflect@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.5.30
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.5.30
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.5.1
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.5.1
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.2.2
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.2.2
	- particlerain@1.3.0
	- reeses-sodium-options@1.1.2
	- roughlyenoughitems@6.0.264-alpha
	- searchablecontainers@1.3
	- shulkerboxtooltip@3.0.1+1.17
	- skinshine@1.1.9
	- slotlock@1.0.4-BETA+1.17
	- sodium@0.3.0+IRIS2
	- sodium-extra@0.3.3
	- spruceui@3.3.0+1.17
	- starlight@1.0.0-RC3+fabric.2b7d7ae
	- tooltipfix@1.0.3-1.16
	- torohealth@1.17.1-fabric-12
	- tweakeroo@0.10.0-dev.20210710.155746
	- tweed4_annotated@1.2.0
	- tweed4_base@1.3.1
	- tweed4_data@1.2.0
	- tweed4_data_hjson@1.1.0
	- tweed4_tailor_coat@1.0.1
	- tweed4_tailor_screen@1.0.1
	- user11681_reflect@2.0.0
	- wi_zoom@1.3-MC1.17.1
	- worldedit@7.2.6+4b2d1e7
	- wthit@3.8.1
	- xaerominimap@21.16.0
	- xaeroworldmap@1.16.1
```
* Crash log (Not Enough Crashes)
```
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: Failed to instantiate language adapter: kbootstrap
	at net.fabricmc.loader.FabricLoader.setupLanguageAdapters(FabricLoader.java:394)
	at net.fabricmc.loader.FabricLoader.finishModLoading(FabricLoader.java:249)
	at net.fabricmc.loader.FabricLoader.freeze(FabricLoader.java:105)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:133)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at net.fabricmc.loader.FabricLoader.setupLanguageAdapters(FabricLoader.java:392)
	... 12 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "version" is null
	at net.auoeke.kbootstrap.Downloader.download(Downloader.java:138)
	at net.auoeke.kbootstrap.Adapter.<init>(Adapter.kt:114)
	... 18 more
Caused by: java.lang.NullPointerException: Cannot invoke "String.split(String)" because "version" is null
	at net.auoeke.kbootstrap.Downloader.parseVersion(Downloader.java:48)
	at net.auoeke.kbootstrap.Downloader.libraryVersion(Downloader.java:37)
	at net.auoeke.kbootstrap.Downloader.download(Downloader.java:114)
	... 19 more
```

Seems something "version" is leaked in json.

**Comment by auoeke** [comment]
Is this better? https://modrinth.com/mod/limitless/version/N7W5MTvM

**Comment by craftingmod** [comment]
> Is this better? https://modrinth.com/mod/limitless/version/N7W5MTvM

Crash is fixed :+1: Thanks!

**Comment by auoeke** [comment]
Thanks for reporting.
