### ISSUE TITLE
Server crashes on startup using v1.5.13

### ISSUE THREAD

**Issue by CozzyBro2** [auoeke/limitless#63]
Server diagnostics:

* Minecraft Version: 1.17.1
* Fabric Version: 0.12.5 
* Fabric API Version: 0.42.1 
* Limitless Version: 1.5.13 

Terminal output from starting the server:
```
[gavin@archlinux ~]$ mc-server.sh
[14:26:54] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.17.1
[14:26:54] [main/INFO]: Loading for game Minecraft 1.17.1
[14:26:55] [main/WARN]: Warnings were found!
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[14:26:55] [main/INFO]: Loading 71 mods:
	- blue_endless_jankson 1.2.1
	- c2me 0.2.0+alpha.5.0
	- chathistory 1.2.0
	- cloth-basic-math 0.5.1
	- cloth-config 6.0.39
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT
	- dungeons_arise 2.1.48-fabric
	- fabric 0.42.1+1.17
	- fabric-api-base 0.4.0+5847535018
	- fabric-api-lookup-api-v1 1.3.1+5847535018
	- fabric-biome-api-v1 3.2.2+5847535018
	- fabric-command-api-v1 1.1.4+5847535018
	- fabric-commands-v0 0.2.3+5847535018
	- fabric-containers-v0 0.1.13+5847535018
	- fabric-content-registries-v0 0.3.1+5847535018
	- fabric-crash-report-info-v1 0.1.6+5847535018
	- fabric-dimensions-v1 2.0.13+5847535018
	- fabric-entity-events-v1 1.3.1+5847535018
	- fabric-events-interaction-v0 0.4.11+5847535018
	- fabric-events-lifecycle-v0 0.2.2+5847535018
	- fabric-game-rule-api-v1 1.0.8+5847535018
	- fabric-item-api-v1 1.2.5+5847535018
	- fabric-item-groups-v0 0.3.1+5847535018
	- fabric-lifecycle-events-v1 1.4.5+5847535018
	- fabric-loot-tables-v1 1.0.5+5847535018
	- fabric-mining-level-api-v1 1.0.2+6d0fac4218
	- fabric-mining-levels-v0 0.1.5+6d0fac4218
	- fabric-networking-api-v1 1.0.14+5847535018
	- fabric-networking-blockentity-v0 0.2.12+5847535018
	- fabric-networking-v0 0.3.3+5847535018
	- fabric-object-builder-api-v1 1.10.11+6d0fac4218
	- fabric-object-builders-v0 0.7.5+6d0fac4218
	- fabric-particles-v1 0.2.5+5847535018
	- fabric-permissions-api-v0 0.1-SNAPSHOT
	- fabric-registry-sync-v0 0.7.13+5847535018
	- fabric-rendering-data-attachment-v1 0.1.6+5847535018
	- fabric-rendering-fluids-v1 0.2.1+6d0fac4218
	- fabric-resource-loader-v0 0.4.9+5847535018
	- fabric-screen-handler-api-v1 1.1.9+5847535018
	- fabric-structure-api-v1 1.1.14+5847535018
	- fabric-tag-extensions-v0 1.2.2+5847535018
	- fabric-tool-attribute-api-v1 1.3.1+eb76084f18
	- fabric-transfer-api-v1 1.5.1+6d0fac4218
	- fabricloader 0.12.5
	- fastfurnace 1.17-3.0
	- flan 1.17.1-1.6.2
	- hlandbukkit_c2me-fabric_ver_1_17_libs_ 0.2.0+alpha.5.0
	- huntingham-hills 1.2.8
	- hydrogen 0.3
	- inventorysorter 1.8.0-1.17
	- java 17
	- kbootstrap 0.1.5
	- krypton 0.1.4
	- kyrptconfig 1.1.10-1.17
	- limitless 1.5.13
	- lithium 0.7.5
	- minecraft 1.17.1
	- mostructures 1.3.0-pre1-1.17.1
	- net_auoeke_extensions_asm-tree 0.24.0
	- net_auoeke_extensions_extensions 0.24.0
	- net_auoeke_reflect 3.2.0
	- net_bytebuddy_byte-buddy-agent 1.11.21
	- net_gudenau_lib_unsafe 1.4.3
	- omega-config 1.0.8
	- playerless final
	- repurposed_structures 2.5.5+1.17.1
	- semblance 1.0.0
	- spark 1.6.2
	- srch 1.1
	- starlight 1.0.0+fabric.73f6d37
	- vanish 1.2.6
[14:26:55] [main/WARN]: Mod `playerless` (final) does not respect SemVer - comparison support is limited.
[14:26:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/home/gavin/Desktop/Minecraft-Server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[14:26:56] [main/INFO]: Compatibility level set to JAVA_16
[14:26:56] [main/INFO]: Configuration loaded successfully after 215.200988ms
[14:26:56] [main/INFO]: Successfully loaded configuration for C2ME
[14:26:56] [main/INFO]: Searching for modules in 2 locations...
[14:26:56] [main/INFO]: Loading 1 modules: [C2ME.fabric.libs.main]
[14:26:56] [main/WARN]: Error while loading submodule
java.lang.module.FindException: Module jdk.incubator.vector not found, required by C2ME.fabric.libs.main
	at java.lang.module.Resolver.findFail(Resolver.java:893) ~[?:?]
	at java.lang.module.Resolver.resolve(Resolver.java:192) ~[?:?]
	at java.lang.module.Resolver.resolve(Resolver.java:141) ~[?:?]
	at java.lang.module.Configuration.resolve(Configuration.java:421) ~[?:?]
	at java.lang.module.Configuration.resolve(Configuration.java:255) ~[?:?]
	at com.ishland.c2me.common.util.ModuleUtil.<clinit>(ModuleUtil.java:48) [pacmc_modrinth_VSNURh3q_4FLwGDDE_0.jar:?]
	at com.ishland.c2me.mixin.C2MEMixinPlugin.onLoad(C2MEMixinPlugin.java:24) [pacmc_modrinth_VSNURh3q_4FLwGDDE_0.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.onLoad(PluginHandle.java:119) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:709) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) [?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [fabric-server-launch.jar:?]
[14:26:56] [main/INFO]: Initializing C2ME Compatibility Module
Nov 09, 2021 2:26:56 PM net.gudenau.lib.unsafe.Unsafe bind
WARNING: Unable to access Unsafe method (Class,byte[],Object[])Class
java.lang.NoSuchMethodException: no such method: sun.misc.Unsafe.defineAnonymousClass(Class,byte[],Object[])Class/invokeSpecial.
[14:26:57] [main/ERROR]: Error loading companion plugin class [net.auoeke.limitless.transform.Transformer] for mixin config [limitless.mixins.json]. The plugin may be out of date: ExceptionInInitializerError:null
java.lang.ExceptionInInitializerError: null
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.findClass(MixinServiceKnot.java:96) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:708) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) [?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [fabric-server-launch.jar:?]
Caused by: java.lang.IllegalStateException: Could not self-attach to current VM using external process
	at net.bytebuddy.agent.ByteBuddyAgent.installExternal(ByteBuddyAgent.java:695) ~[net_bytebuddy_byte-buddy-agent-1.11.21-679d72d3768c9acd.jar:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:626) ~[net_bytebuddy_byte-buddy-agent-1.11.21-679d72d3768c9acd.jar:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:606) ~[net_bytebuddy_byte-buddy-agent-1.11.21-679d72d3768c9acd.jar:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:558) ~[net_bytebuddy_byte-buddy-agent-1.11.21-679d72d3768c9acd.jar:?]
	at net.bytebuddy.agent.ByteBuddyAgent.install(ByteBuddyAgent.java:535) ~[net_bytebuddy_byte-buddy-agent-1.11.21-679d72d3768c9acd.jar:?]
	at net.auoeke.limitless.transform.Transformer.<clinit>(Transformer.kt:154) ~[pacmc_modrinth_Qx0jUYY8_nuFDStBb_0.jar:?]
	... 32 more
[14:26:57] [main/INFO]: Loaded configuration file for Lithium: 87 options available, 1 override(s) found
[14:26:57] [main/WARN]: Catching java.lang.ClassNotFoundException: draylar/horizon/world/RockySurfaceBuilder
java.lang.ClassNotFoundException: draylar/horizon/world/RockySurfaceBuilder
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:65) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:76) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:71) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2022) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1018) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) [?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [fabric-server-launch.jar:?]
[14:26:57] [main/WARN]: Error loading class: draylar/horizon/world/RockySurfaceBuilder (java.lang.ClassNotFoundException: draylar/horizon/world/RockySurfaceBuilder)
[14:26:57] [main/WARN]: Catching java.lang.ClassNotFoundException: draylar/horizon/world/MinersHorizonChunkGenerator
java.lang.ClassNotFoundException: draylar/horizon/world/MinersHorizonChunkGenerator
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:65) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:76) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:71) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2022) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1018) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) [?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:134) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60) [fabric-server-launch.jar:?]
[14:26:57] [main/WARN]: Error loading class: draylar/horizon/world/MinersHorizonChunkGenerator (java.lang.ClassNotFoundException: draylar/horizon/world/MinersHorizonChunkGenerator)
[14:26:58] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[14:26:58] [main/INFO]: Adding mixins: [None]
[14:26:58] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableMapEntry' (url: jar:file:/home/gavin/Desktop/Minecraft-Server/mods/pacmc_modrinth_AZomiSrC_gqJWYgtD_0.jar!/com/google/common/collect/HydrogenImmutableMapEntry.class)
[14:26:58] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySetIterator' (url: jar:file:/home/gavin/Desktop/Minecraft-Server/mods/pacmc_modrinth_AZomiSrC_gqJWYgtD_0.jar!/com/google/common/collect/HydrogenEntrySetIterator.class)
[14:26:58] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenEntrySet' (url: jar:file:/home/gavin/Desktop/Minecraft-Server/mods/pacmc_modrinth_AZomiSrC_gqJWYgtD_0.jar!/com/google/common/collect/HydrogenEntrySet.class)
[14:26:58] [main/INFO]: Injecting class 'com.google.common.collect.HydrogenImmutableReferenceHashMap' (url: jar:file:/home/gavin/Desktop/Minecraft-Server/mods/pacmc_modrinth_AZomiSrC_gqJWYgtD_0.jar!/com/google/common/collect/HydrogenImmutableReferenceHashMap.class)
[14:26:58] [main/INFO]: Transforming Lnet/minecraft/class_128;<init>(Ljava/lang/String;Ljava/lang/Throwable;)V
[14:26:58] [main/INFO]: Transforming Lnet/minecraft/class_128;<clinit>()V
[14:27:03] [main/INFO]: Transforming Lnet/minecraft/class_3085;<init>(Lcom/mojang/serialization/Codec;)V
[14:27:03] [main/INFO]: Transforming Lnet/minecraft/class_3085;<clinit>()V
[14:27:04] [main/INFO]: Replacing lithium chunk_access method getChunkOffThread to apply non-blocking async chunk request
```
The error in question appears on the fabric loader, which shows this stack trace:
```
java.lang.AbstractMethodError: Receiver class net.minecraft.class_1900 does not define or inherit an implementation of the resolved method 'abstract int limitless_getOriginalMaxLevel()' of interface net.auoeke.limitless.transform.access.EnchantmentAccess.
	at net.minecraft.class_2370.handler$zlj000$initializeEnchantment(class_2370.java:1521)
	at net.minecraft.class_2370.method_31051(class_2370.java:98)
	at net.minecraft.class_2370.method_10273(class_2370.java:72)
	at net.minecraft.class_2370.method_10272(class_2370.java:103)
	at net.minecraft.class_2378.method_10230(class_2378.java:430)
	at net.minecraft.class_2378.method_10226(class_2378.java:426)
	at net.minecraft.class_1893.method_8235(class_1893.java:69)
	at net.minecraft.class_1893.<clinit>(class_1893.java:15)
	at net.minecraft.class_2378.method_10243(class_2378.java:174)
	at net.minecraft.class_2378.method_34031(class_2378.java:275)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
	at net.minecraft.class_2378.<clinit>(class_2378.java:274)
	at net.minecraft.class_2966.method_12851(class_2966.java:44)
	at net.minecraft.server.Main.main(Main.java:92)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60)

```
The server starts as expected without limitless.
All mods were installed and managed by [pacmc](https://github.com/jakobkmar/pacmc)

**Comment by auoeke** [comment]
I don't know what I changed in the release for Minecraft 1.18 but it seems to work properly with server and client.

**Comment by auoeke** [comment]
I just noticed the other mods. I tested only with Fabric API so YMMV.
