### ISSUE TITLE
Limitless instant crash on launch (1.17.1)

### ISSUE THREAD

**Issue by Broekinator** [auoeke/limitless#71]
I used the versions 1.6.0 and 1.5.17 to try and see if an older version would fix this issue but no. 
This is the stacktrace I get when starting up my server (it instant crashes without even loading in the worlds):

net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchMethodError: 'net.minecraft.class_6489 net.minecraft.class_155.method_16673()'
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_6489 net.minecraft.class_155.method_16673()'
	at net.fabricmc.fabric.impl.resource.loader.FabricModResourcePack.method_14410(FabricModResourcePack.java:49)
	at net.fabricmc.fabric.impl.resource.loader.FabricModResourcePack.method_14407(FabricModResourcePack.java:75)
	at net.minecraft.class_3288.method_14456(class_3288.java:37)
	at net.fabricmc.fabric.impl.resource.loader.ModResourcePackCreator.method_14453(ModResourcePackCreator.java:78)
	at net.minecraft.class_3283.method_29212(class_3283.java:45)
	at net.minecraft.class_3283.method_14445(class_3283.java:38)
	at net.minecraft.server.MinecraftServer.method_29736(MinecraftServer.java:1358)
	at net.minecraft.server.Main.main(Main.java:146)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	... 7 more

I really don't know what to do, and I have tried almost everything to bypass this, but it just won't, Please help me with this.

**Comment by auoeke** [comment]
Fixed in 1.6.3-1.17.1.
